const bios = [
  "doesn't return library books on time.",
  "likes to ruin the end of movies.",
  "has been known to sneeze at the buffet.",
  "steals candy from babies and then throws the candy in the trash—in front of them!",
  "only speaks in passive-aggressive voice.",
  "will point out your least favorite body parts.",
  "leaves one square of hay for the next pony and calls it 'sharing.'",
  "corrects your grammar mid-argument, then loses the argument anyway.",
  "claims they 'hate drama' while starting three group chats about you.",
  "double-dips at every dip. Triple-dips if no one is looking.",
  "says 'per my last email' out loud in real life.",
  "schedules a 'quick sync' that could have been a single sentence.",
  "replies 'k.' to paragraphs you spent twenty minutes writing.",
  "claps when the plane lands and expects a standing ovation.",
  "talks through the whole movie, then asks what happened.",
  "leaves shopping carts in the middle of the parking lot 'for exercise.'",
  "microwaves fish in the shared pasture break room.",
  "tags you in photos where you're blinking and eating at the same time.",
  "plays the ukulele badly and calls it a 'vibe.'",
  "says 'we should hang out soon' with zero intention of ever hanging out.",
  "borrows your glitter and returns it mixed with... something.",
  "laughs at their own jokes before the punchline lands.",
  "types 'no offense' and then says the most offensive thing possible.",
  "still uses speakerphone in public. Loudly. About personal topics.",
  "leaves read receipts on but never responds—it's a power move.",
  "insists on splitting the bill evenly after ordering the most expensive salad.",
  "gives backhanded compliments like they're doing you a favor.",
  "whispers 'you're actually brave for wearing that' at formal events.",
  "chews ice during important speeches. On purpose.",
  "claims to be 'brutally honest' but is mostly just brutal.",
  "leaves one sip in the oat milk carton and puts it back.",
  "sends voice notes that are ninety percent throat clearing.",
  "interrupts your story to tell a worse version of their own story.",
  "says they're 'not a rules pony' while cutting every line.",
  "reports lost items as 'stolen' for the drama.",
  "refers to themselves in the third person during apologies.",
  "apologizes with 'sorry you feel that way' and thinks that counts.",
  "hums the same six notes of a song you hate. All day.",
  "leaves party decorations up until the next solstice 'for ambiance.'",
  "comments 'who?' under posts about beloved community figures.",
  "eats the last cupcake and leaves the empty box as a cruel museum piece.",
];

export { bios };
