const suffixes = [
  // Original
  "the Killer",
  "the Destroyer",
  "the Soul Smasher",
  "the Dream Crusher",
  "the Bloody",
  "Grimdancer",
  "Dream Eater",
  "Dream Ender",
  "Life Eater",
  "Hoof Smasher",
  "the Blood Soaked",
  "the Blood Drinker",
  // Added — “the …”
  "the Mane Ripper",
  "the Pasture's End",
  "the Last Gallop",
  "the Sugar Rot",
  "the Ribbon Cutter",
  "the Sparkle Snuffer",
  "the Friendship Ender",
  "the Wink That Kills",
  "the Cotton Candy Carnage",
  "the Cutie Marked for Death",
  // Added — Ender / Eater / Breaker
  "Hope Ender",
  "Joy Ender",
  "Song Ender",
  "Star Eater",
  "Rainbow Eater",
  "Laughter Ender",
  "Heartbreaker",
  "Harmony Breaker",
  // Added — Hoof / arena
  "Hoof of Doom",
  "Iron Hoof",
  "the Trampler",
  "the Stomper",
  "Mane Shredder",
  "Tail Whip Terror",
  // Added — Grim cute
  "Grave Dancer",
  "Ash Princess",
  "Rust & Stardust",
  "Bittersweet Reaper",
  "Velvet Guillotine",
  "Lace & Lacerations",
  // Added — Blood / wound
  "the Red Tide",
  "the Open Wound",
  "Scar Tissue",
  "the Bleeding Heart",
  // Added — One-word titles
  "Gloomgallop",
  "Dreadmare",
  "Rotwhisper",
  "Hollowhoof",
  "Nighttrot",
];

export { suffixes };
